ALTER TABLE cal_bsm
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_cavi
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_cen
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_ecg
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_esu1
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_fetal
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_infant_incu
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_nibp
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_pace
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_po
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_pressure
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_spiro
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_temp
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;

ALTER TABLE cal_traction
ADD Room_T FLOAT(4) NOT NULL
AFTER Caldate
, ADD Room_H FLOAT(4) NOT NULL
AFTER Room_T;